import { StyleSheet } from "@react-pdf/renderer";

export const templateStyles = StyleSheet.create({
  page: { padding: 30, fontSize: 11, fontFamily: "Helvetica" },
  header: { marginBottom: 13, paddingBottom: 8 },
  name: { fontSize: 20, fontWeight: "bold", marginBottom: 2 },
  desiredRole: {
    fontSize: 13,
    color: "#2563eb",
    fontWeight: "bold",
    marginBottom: 8,
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 2,
  },
  contactItem: { fontSize: 10, color: "#374151", marginRight: 12 },
  separator: { fontSize: 12, color: "#d1d5db", marginHorizontal: 8 },
  linksRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 2,
    marginBottom: 2,
  },
  linkItem: {
    fontSize: 9,
    color: "#2563eb",
    textDecoration: "underline",
    marginRight: 20,
    marginBottom: 2,
  },
  section: { marginBottom: 13 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#1e293b",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 1,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    borderBottomStyle: "solid",
    paddingBottom: 4,
  },
  expBlock: {
    marginBottom: 12,
    paddingBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#e5e7eb",
    borderBottomStyle: "solid",
  },
  roleAndDate: {
    fontSize: 10,
    color: "#64748b",
    marginBottom: 2,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  roleAndCompany: { fontSize: 11, color: "#0f172a", flexDirection: "row" },
  jobRole: { fontSize: 11, fontWeight: "bold", color: "#0f172a" },
  companyName: { fontSize: 11, color: "#64748b" },
  companySeparator: { fontSize: 11, color: "#64748b" },
  dateRange: { fontSize: 10, color: "#64748b" },
  tech: { fontSize: 10, color: "#2563eb", marginBottom: 2 },
  activities: { fontSize: 10, marginBottom: 2, marginLeft: 8 },
  results: {
    fontSize: 10,
    fontStyle: "italic",
    marginLeft: 8,
    marginBottom: 2,
  },
  eduBlock: {
    marginBottom: 12,
    paddingBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#e5e7eb",
    borderBottomStyle: "solid",
  },
  eduTitle: { fontSize: 11, fontWeight: "bold", color: "#0f172a" },
  eduInst: { fontSize: 10, color: "#64748b", marginBottom: 2 },
  eduDesc: { fontSize: 10, marginLeft: 8, marginBottom: 2 },
  skillsLangRow: { flexDirection: "row", gap: 32, marginBottom: 13 },
  skillsCol: { flex: 1, marginRight: 16 },
  langCol: { flex: 1 },
  skillText: { fontSize: 10, color: "#0f172a", marginBottom: 2 },
  langRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  langItem: { fontSize: 10, marginRight: 12 },
  certBlock: {
    marginBottom: 12,
    paddingBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#e5e7eb",
    borderBottomStyle: "solid",
  },
  certName: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#0f172a",
    marginBottom: 2,
  },
  certDate: {
    fontSize: 10,
    fontStyle: "italic",
    color: "#64748b",
    marginLeft: 4,
  },
  certIssuer: { fontSize: 10, color: "#64748b", marginBottom: 2 },
  certLink: {
    fontSize: 9,
    color: "#2563eb",
    textDecoration: "underline",
    marginBottom: 2,
  },
  certDesc: { fontSize: 10, marginLeft: 8, marginBottom: 2 },
  projBlock: {
    marginBottom: 12,
    paddingBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#e5e7eb",
    borderBottomStyle: "solid",
  },
  projName: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#0f172a",
    marginBottom: 2,
  },
  projYear: { fontSize: 10, color: "#64748b", marginLeft: 4 },
  projTech: { fontSize: 10, color: "#2563eb", marginBottom: 2 },
  projDesc: { fontSize: 10, marginLeft: 8, marginBottom: 2 },
  projLink: {
    fontSize: 9,
    color: "#2563eb",
    textDecoration: "underline",
    marginLeft: 8,
  },
  volBlock: {
    marginBottom: 12,
    paddingBottom: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: "#e5e7eb",
    borderBottomStyle: "solid",
  },
  volRole: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#0f172a",
    marginBottom: 2,
  },
  volOrg: { fontSize: 10, color: "#64748b", marginBottom: 2 },
  volDesc: { fontSize: 10, marginLeft: 8, marginBottom: 2 },
  volImpact: {
    fontSize: 10,
    fontStyle: "italic",
    marginLeft: 8,
    marginBottom: 2,
  },
});
