import { StyleSheet } from "@react-pdf/renderer";

export const templateStyles = StyleSheet.create({
  page: {
    padding: 0,
    fontSize: 10,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
  },
  // App-level layout (offset layout using fixed sidebar background)
  mainWithSidebarOffset: {
    padding: 30,
    marginLeft: 190,
  },
  sidebarContentAbs: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 190,
    padding: 24,
    color: "#ffffff",
  },
  header: {
    backgroundColor: "#ec4899",
    padding: 30,
    color: "#ffffff",
  },
  name: {
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#ffffff",
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  desiredRole: {
    fontSize: 16,
    color: "#fdf2f8",
    fontWeight: "bold",
    marginBottom: 15,
    fontStyle: "italic",
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 4,
    flexWrap: "wrap",
  },
  contactItem: {
    fontSize: 10,
    color: "#fdf2f8",
    marginRight: 15,
  },
  separator: {
    fontSize: 10,
    color: "#fbcfe8",
    marginHorizontal: 8,
  },
  linksRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
  },
  linkItem: {
    fontSize: 10,
    color: "#ffffff",
    textDecoration: "underline",
    marginRight: 20,
    marginBottom: 4,
    backgroundColor: "rgba(255,255,255,0.1)",
    padding: 4,
    borderRadius: 3,
  },
  content: {
    padding: 30,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#3b82f6",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    borderBottomWidth: 2,
    borderBottomColor: "#3b82f6",
    borderBottomStyle: "solid",
    paddingBottom: 6,
  },
  // Sidebar extras
  monogramCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  monogramText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#ffffff",
    letterSpacing: 1,
  },
  sidebarSectionTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#ffffff",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 16,
    marginBottom: 8,
  },
  sidebarText: {
    fontSize: 10,
    color: "#fdf2f8",
    marginBottom: 6,
  },
  divider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.25)",
    marginVertical: 12,
  },
  // Bars (used for languages)
  barBg: {
    height: 6,
    backgroundColor: "rgba(255,255,255,0.25)",
    borderRadius: 3,
    overflow: "hidden",
  },
  barFill: {
    height: 6,
    backgroundColor: "#ffffff",
    borderRadius: 3,
  },
  summary: {
    fontSize: 11,
    color: "#374151",
    lineHeight: 1.5,
    marginBottom: 20,
    backgroundColor: "#dbeafe",
    padding: 15,
    borderRadius: 8,
  },
  expBlock: {
    marginBottom: 15,
    paddingBottom: 12,
    backgroundColor: "#fafafa",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#ec4899",
    borderLeftStyle: "solid",
  },
  roleAndDate: {
    fontSize: 10,
    color: "#6b7280",
    marginBottom: 4,
  },
  metaLine: {
    fontSize: 10,
    color: "#6b7280",
  },
  titleLine: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#ec4899",
  },
  roleAndCompany: {
    fontSize: 11,
    color: "#1f2937",
    flexDirection: "row",
  },
  jobRole: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#ec4899",
  },
  companyName: {
    fontSize: 11,
    color: "#6b7280",
  },
  companySeparator: {
    fontSize: 11,
    color: "#6b7280",
  },
  dateRange: {
    fontSize: 10,
    color: "#6b7280",
    backgroundColor: "#f3f4f6",
    padding: 3,
    borderRadius: 3,
  },
  tech: {
    fontSize: 10,
    color: "#3b82f6",
    marginBottom: 6,
    fontWeight: "bold",
    backgroundColor: "#fdf2f8",
    padding: 4,
    borderRadius: 3,
  },
  activities: {
    fontSize: 10,
    marginBottom: 4,
    marginLeft: 0,
    color: "#374151",
  },
  results: {
    fontSize: 10,
    fontStyle: "italic",
    marginLeft: 0,
    marginBottom: 4,
    color: "#059669",
    backgroundColor: "#f0fdf4",
    padding: 4,
    borderRadius: 3,
  },
  eduBlock: {
    marginBottom: 15,
    paddingBottom: 12,
    backgroundColor: "#fafafa",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#10b981",
    borderLeftStyle: "solid",
  },
  eduTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#10b981",
  },
  eduInst: {
    fontSize: 10,
    color: "#6b7280",
    marginBottom: 4,
  },
  eduDesc: {
    fontSize: 10,
    marginLeft: 0,
    marginBottom: 4,
    color: "#374151",
  },
  skillsLangRow: {
    flexDirection: "row",
    gap: 25,
    marginBottom: 20,
  },
  skillsCol: {
    flex: 1,
    marginRight: 15,
  },
  skillsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 3,
  },
  langCol: {
    flex: 1,
  },
  skillText: {
    fontSize: 9,
    color: "#1f2937",
    marginBottom: 3,
    marginRight: 6,
    backgroundColor: "#f3f4f6",
    padding: 4,
    borderRadius: 12,
    textAlign: "center",
  },
  langRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  langItem: {
    fontSize: 10,
    marginRight: 8,
    backgroundColor: "#f3f4f6",
    padding: 6,
    borderRadius: 15,
    textAlign: "center",
  },
  certBlock: {
    marginBottom: 15,
    paddingBottom: 12,
    backgroundColor: "#fafafa",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#f59e0b",
    borderLeftStyle: "solid",
  },
  certName: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#f59e0b",
    marginBottom: 4,
  },
  certDate: {
    fontSize: 10,
    fontStyle: "italic",
    color: "#6b7280",
    marginLeft: 0,
  },
  certIssuer: {
    fontSize: 10,
    color: "#6b7280",
    marginBottom: 4,
  },
  certLink: {
    fontSize: 10,
    color: "#ec4899",
    textDecoration: "underline",
    marginBottom: 4,
  },
  certDesc: {
    fontSize: 10,
    marginLeft: 0,
    marginBottom: 4,
    color: "#374151",
  },
  projBlock: {
    marginBottom: 15,
    paddingBottom: 12,
    backgroundColor: "#fafafa",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#8b5cf6",
    borderLeftStyle: "solid",
  },
  projName: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#8b5cf6",
    marginBottom: 4,
  },
  projYear: {
    fontSize: 10,
    color: "#6b7280",
    marginLeft: 0,
  },
  volBlock: {
    marginBottom: 15,
    paddingBottom: 12,
    backgroundColor: "#fafafa",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#ef4444",
    borderLeftStyle: "solid",
  },
  volRole: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#ef4444",
    marginBottom: 4,
  },
  volOrg: {
    fontSize: 10,
    color: "#6b7280",
    marginBottom: 4,
  },
  volDesc: {
    fontSize: 10,
    marginLeft: 0,
    marginBottom: 4,
    color: "#374151",
  },
  volImpact: {
    fontSize: 10,
    fontStyle: "italic",
    marginLeft: 0,
    marginBottom: 4,
    color: "#059669",
  },
  projTech: {
    fontSize: 10,
    color: "#3b82f6",
    marginBottom: 6,
    fontWeight: "bold",
    backgroundColor: "#fdf2f8",
    padding: 4,
    borderRadius: 3,
  },
  projDesc: {
    fontSize: 10,
    marginLeft: 0,
    marginBottom: 4,
    color: "#374151",
  },
  projLink: {
    fontSize: 10,
    color: "#3b82f6",
    textDecoration: "underline",
    marginLeft: 0,
  },
  // First page wide background strip (non-fixed)
  firstPageWideStrip: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 190,
    backgroundColor: "#3b82f6",
  },
  // Fixed background strip for all pages
  bgStrip: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 80,
    backgroundColor: "#3b82f6",
  },
});
