import { StyleSheet } from "@react-pdf/renderer";
import { BaseTheme } from "../../theme";
import { CvTheme } from "../../types";

export const getStyles = (theme?: CvTheme) => {
  const finalTheme = { ...BaseTheme, ...theme };

  return StyleSheet.create({
    page: {
      padding: 30,
      fontSize: 10,
      fontFamily: "Helvetica",
      backgroundColor: "#ffffff",
    },
    header: {
      marginBottom: 20,
      paddingBottom: 15,
      borderBottomWidth: 2,
      borderBottomColor: finalTheme.color,
      borderBottomStyle: "solid",
    },
    name: {
      fontSize: 24,
      fontWeight: "bold",
      marginBottom: 4,
      color: "#1f2937",
    },
    desiredRole: {
      fontSize: 14,
      color: finalTheme.color,
      fontWeight: "bold",
      marginBottom: 8,
      textTransform: "uppercase",
      letterSpacing: 1,
    },
    contactRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-start",
      marginBottom: 3,
      flexWrap: "wrap",
    },
    contactItem: {
      fontSize: 9,
      color: "#6b7280",
      marginRight: 15,
    },
    separator: {
      fontSize: 9,
      color: "#d1d5db",
      marginHorizontal: 8,
    },
    linksRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: 8,
    },
    linkItem: {
      fontSize: 9,
      color: finalTheme.color,
      textDecoration: "none",
      marginRight: 20,
      marginBottom: 3,
    },
    section: {
      marginBottom: 15,
    },
    sectionTitle: {
      fontSize: 12,
      fontWeight: "bold",
      color: "#1f2937",
      marginBottom: 8,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      borderBottomWidth: 1,
      borderBottomColor: "#e5e7eb",
      borderBottomStyle: "solid",
      paddingBottom: 4,
    },
    expBlock: {
      marginBottom: 12,
      paddingBottom: 8,
      borderLeftWidth: 3,
      borderLeftColor: finalTheme.color,
      borderLeftStyle: "solid",
      paddingLeft: 12,
    },
    roleAndDate: {
      fontSize: 9,
      color: "#6b7280",
      marginBottom: 3,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    roleAndCompany: {
      fontSize: 10,
      color: "#1f2937",
      flexDirection: "row",
      alignItems: "center",
    },
    jobRole: {
      fontSize: 10,
      fontWeight: "bold",
      color: "#1f2937",
    },
    companyName: {
      fontSize: 10,
      color: "#6b7280",
    },
    companySeparator: {
      fontSize: 10,
      color: "#6b7280",
      marginLeft: 6,
      marginRight: 2,
    },
    dateRange: {
      fontSize: 9,
      color: "#6b7280",
    },
    tech: {
      fontSize: 9,
      color: finalTheme.color,
      marginBottom: 4,
      fontWeight: "bold",
    },
    activities: {
      fontSize: 9,
      marginBottom: 3,
      marginLeft: 0,
      color: "#374151",
    },
    results: {
      fontSize: 9,
      fontStyle: "italic",
      marginLeft: 0,
      marginBottom: 3,
      color: finalTheme.color,
    },
    eduBlock: {
      marginBottom: 12,
      paddingBottom: 8,
      borderLeftWidth: 3,
      borderLeftColor: finalTheme.color,
      borderLeftStyle: "solid",
      paddingLeft: 12,
    },
    eduTitle: {
      fontSize: 10,
      fontWeight: "bold",
      color: "#1f2937",
    },
    eduInst: {
      fontSize: 9,
      color: "#6b7280",
      marginBottom: 3,
    },
    eduDesc: {
      fontSize: 9,
      marginLeft: 0,
      marginBottom: 3,
      color: "#374151",
    },
    skillsLangRow: {
      flexDirection: "row",
      gap: 30,
      marginBottom: 15,
    },
    skillsCol: {
      flex: 1,
      marginRight: 20,
    },
    skillsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 4,
    },
    langCol: {
      flex: 1,
    },
    skillText: {
      fontSize: 9,
      color: "#1f2937",
      marginBottom: 2,
      marginRight: 8,
      backgroundColor: "#f3f4f6",
      padding: 3,
      borderRadius: 3,
    },
    langRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    langItem: {
      fontSize: 9,
      marginRight: 10,
      backgroundColor: "#f3f4f6",
      padding: 4,
      borderRadius: 3,
    },
    certBlock: {
      marginBottom: 12,
      paddingBottom: 8,
      borderLeftWidth: 3,
      borderLeftColor: finalTheme.color,
      borderLeftStyle: "solid",
      paddingLeft: 12,
    },
    certName: {
      fontSize: 10,
      fontWeight: "bold",
      color: "#1f2937",
      marginBottom: 3,
    },
    certDate: {
      fontSize: 9,
      fontStyle: "italic",
      color: "#6b7280",
      marginLeft: 0,
    },
    certIssuer: {
      fontSize: 9,
      color: "#6b7280",
      marginBottom: 3,
    },
    certLink: {
      fontSize: 9,
      color: finalTheme.color,
      textDecoration: "none",
      marginBottom: 3,
    },
    certDesc: {
      fontSize: 9,
      marginLeft: 0,
      marginBottom: 3,
      color: "#374151",
    },
    projBlock: {
      marginBottom: 12,
      paddingBottom: 8,
      borderLeftWidth: 3,
      borderLeftColor: finalTheme.color,
      borderLeftStyle: "solid",
      paddingLeft: 12,
    },
    projName: {
      fontSize: 10,
      fontWeight: "bold",
      color: "#1f2937",
      marginBottom: 3,
    },
    projYear: {
      fontSize: 9,
      color: "#6b7280",
      marginLeft: 0,
    },
    projTech: {
      fontSize: 9,
      color: finalTheme.color,
      marginBottom: 4,
      fontWeight: "bold",
    },
    projDesc: {
      fontSize: 9,
      marginLeft: 0,
      marginBottom: 3,
      color: "#374151",
    },
    projLink: {
      fontSize: 9,
      color: finalTheme.color,
      textDecoration: "none",
      marginLeft: 0,
    },
    volBlock: {
      marginBottom: 12,
      paddingBottom: 8,
      borderLeftWidth: 3,
      borderLeftColor: finalTheme.color,
      borderLeftStyle: "solid",
      paddingLeft: 12,
    },
    volRole: {
      fontSize: 10,
      fontWeight: "bold",
      color: "#1f2937",
      marginBottom: 3,
    },
    volOrg: {
      fontSize: 9,
      color: "#6b7280",
      marginBottom: 3,
    },
    volDesc: {
      fontSize: 9,
      marginLeft: 0,
      marginBottom: 3,
      color: "#374151",
    },
    volImpact: {
      fontSize: 9,
      fontStyle: "italic",
      marginLeft: 0,
      marginBottom: 3,
      color: finalTheme.color,
    },
    summary: {
      fontSize: 10,
      color: "#374151",
      lineHeight: 1.4,
      marginBottom: 15,
    },
  });
};
